name: Publish

on:
  push:
    branches: [master]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn run build
        env:
          NODE_ENV: production
      - run: yarn run test
        env:
          NODE_ENV: test
          MAILEVA_CLIENT_ID: ${{ secrets.MAILEVA_CLIENT_ID }}
          MAILEVA_CLIENT_SECRET: ${{ secrets.MAILEVA_CLIENT_SECRET }}
          MAILEVA_USERNAME: ${{ secrets.MAILEVA_USERNAME }}
          MAILEVA_PASSWORD: ${{ secrets.MAILEVA_PASSWORD }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
